### ISSUE TITLE
When KCL script generates only "root" element - no output is given at all.

### ISSUE THREAD

**Issue by eshepelyuk** [kcl-lang/kcl-py#28]
Related to this thread https://cloud-native.slack.com/archives/C05TC96NWN8/p1707398996760039

## Bug Report

When KCL script generates only "root" element - no output is given at all.

### 1. Minimal reproduce step (Required)

Having KCL file 
```kcl
schema Person:
    name: str = "kcl"
    age: int = 1

Person {
    age = 101
}
```

Using KCL CLI

```sh
> kcl hello.k
name: kcl
age: 101
```

Using python SDK, no output

```sh
> python3 -mkclvm hello.k
```

### 2. What did you expect to see? (Required)

Expect the same outout as from KCL CLI.

### 4. What is your KCL components version? (Required)

```sh
> kcl version
0.7.5-linux-amd64
```

**Comment by Peefy** [comment]
Thank you for your feedback. I will officially resolve it in kcl-py 0.8.
